// tachyon-simd/cpp/simd_scan.h
//
// SIMD-accelerated routines for the tachyon hot path.
// These are the ONLY parts where C/C++ beats Rust — everything else stays in Rust.
//
// Why C++ here specifically:
// 1. picohttpparser's SIMD scanner is battle-tested (H2O, Perl ecosystem)
// 2. SSE4.2 _mm_cmpestri has no stable Rust equivalent with the same codegen
// 3. simdjson's On-Demand API is C++-native with 10+ years of tuning
//
// The cxx bridge ensures: zero-copy, no allocation, type-safe FFI.
//
// NOTE: Shared types (ScanResult, SocketTuning, JsonValue) are defined by the
// cxx bridge in the generated header. Do NOT redefine them here.

#pragma once
#include "rust/cxx.h"
#include <cstdint>
#include <cstddef>

namespace tachyon {
namespace simd {

// Forward declarations — actual definitions are generated by cxx from lib.rs
struct ScanResult;
struct SocketTuning;
struct JsonValue;

// Find \r\n\r\n (end of HTTP headers) using SIMD.
// Falls back to scalar on platforms without SSE4.2.
ScanResult find_header_end_simd(rust::Slice<const uint8_t> buf);

// Find a specific byte in buffer using SIMD (used for ':' in headers, ' ' in
// request line). Equivalent to memchr but tuned for short HTTP strings.
ScanResult find_byte_simd(rust::Slice<const uint8_t> buf, uint8_t needle);

// Validate that a byte range contains only valid HTTP token characters.
// Uses SIMD range checks instead of a lookup table.
// Returns the position of the first invalid byte, or buf.size() if all valid.
size_t validate_token_simd(rust::Slice<const uint8_t> buf);

// Parse JSON from a buffer, extracting top-level string fields.
// Returns empty vec on parse error (no exceptions cross FFI).
rust::Vec<JsonValue> parse_json_fields(rust::Slice<const uint8_t> buf);

// Fast JSON serialization of key-value pairs into a buffer.
// Returns bytes written. Uses SIMD-accelerated string escaping.
size_t serialize_json(
    rust::Slice<const JsonValue> fields,
    rust::Slice<uint8_t> out_buf
);

// Apply all tuning options to a raw file descriptor (Unix) or SOCKET handle (Windows).
// Returns 0 on success, -errno on failure.
// Each option is applied independently — failure of one doesn't block others.
int32_t apply_socket_tuning(int64_t fd, const SocketTuning& tuning);

// Pin the current thread to a specific CPU core (sched_setaffinity on Linux).
// Returns 0 on success, -errno on failure. No-op (returns 0) on non-Linux.
int32_t set_cpu_affinity(int32_t cpu_id);

// Get the number of available CPU cores.
int32_t get_cpu_count();

} // namespace simd
} // namespace tachyon
