/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The Tachyon server instance. Routes are registered in Rust for zero-overhead dispatch. */
export declare class TachyonRawServer {
  constructor(config?: TachyonRawConfig | undefined | null)
  /**
   * Register a route handler. Called once per route at startup from TypeScript.
   *
   * The handler receives a `TachyonRawRequest` and returns a `TachyonRawResponse`.
   * Routing and 404 handling happen entirely in Rust — no JS call for unmatched paths.
   */
  route(method: string, path: string, handler: (arg: TachyonRawRequest) => TachyonRawResponse): void
  /**
   * Start the server. Must be called after all routes are registered.
   *
   * Builds an O(1) route map and starts the Tokio runtime on a background thread.
   */
  listen(): void
}

/** Server configuration exposed to TypeScript. */
export interface TachyonRawConfig {
  bindAddr?: string
  workers?: number
  buffersPerWorker?: number
  bufferSize?: number
  timeoutSecs?: number
  tcpNodelay?: boolean
  reusePort?: boolean
  tcpFastopen?: boolean
  busyPollUs?: number
  recvBufSize?: number
  sendBufSize?: number
  security?: string
  compressionThreshold?: number
}

/** A single HTTP header key-value pair. */
export interface TachyonRawHeader {
  name: string
  value: string
}

/**
 * A typed JSON node for zero-alloc serialization via Rust's JsonWriter.
 * Supports any JSON shape: flat objects, nested objects, arrays, primitives.
 *
 * ```typescript
 * return {
 *   status: 200,
 *   json: [
 *     { key: "message", value: "Hello, World!" },
 *     { key: "id", value: "42", valueType: "number" },
 *     { key: "user", valueType: "object", children: [
 *       { key: "name", value: "Aaron" },
 *       { key: "age", value: "25", valueType: "number" },
 *     ]},
 *     { key: "tags", valueType: "array", children: [
 *       { value: "fast" },
 *       { value: "42", valueType: "number" },
 *     ]},
 *   ],
 * };
 * ```
 */
export interface TachyonRawJsonField {
  /** Object key. Omit for array elements. */
  key?: string
  /** Scalar value as string. Ignored for "object"/"array" types. */
  value?: string
  /** "string" (default) | "number" | "bool" | "null" | "raw" | "object" | "array" */
  valueType?: string
  /** Child fields for "object" or "array" types. */
  children?: Array<TachyonRawJsonField>
}

/**
 * Parsed HTTP request exposed to TypeScript callbacks.
 *
 * ```typescript
 * server.handle(({ method, path, body }) => {
 *     console.log(req.method, req.path);
 *     return { status: 200, body: '{"ok": true}' };
 * });
 * ```
 */
export interface TachyonRawRequest {
  method: string
  path: string
  body?: string
  /** Flat header string: "name\tvalue
  name2\tvalue2
  " — 1 alloc instead of 20+ */
  headers: string
}

/**
 * Response from TypeScript handler.
 *
 * Three response paths (priority: `json` > `array` > `body`):
 *
 * ```typescript
 * // 1. json — object fields, serialized as {...} by Rust's zero-alloc JsonWriter
 * return { status: 200, json: [{ key: "message", value: "sucesso" }] };
 *
 * // 2. array — array elements, serialized as [...] by Rust's zero-alloc JsonWriter
 * return { status: 200, array: [{ value: "item1" }, { value: "42", valueType: "number" }] };
 *
 * // 3. body — plain text or custom content type
 * return { status: 200, body: "Hello!", contentType: "text" };
 * ```
 */
export interface TachyonRawResponse {
  status?: number
  /**
   * Plain body string. Used with `contentType` to set the response type.
   * Lowest priority — ignored if `json` or `array` is present.
   */
  body?: string
  /** "json" | "text" | "html" (default: "json"). Only applies to `body`. */
  contentType?: string
  /** Custom HTTP headers as key-value pairs (e.g., CORS, Cache-Control). */
  headers?: Array<TachyonRawHeader>
  /**
   * JSON object — fields serialized as `{...}` by Rust's zero-alloc JsonWriter.
   * Bypasses `JSON.stringify()` entirely.
   */
  json?: Array<TachyonRawJsonField>
  /** JSON array — elements serialized as `[...]` by Rust's zero-alloc JsonWriter. */
  array?: Array<TachyonRawJsonField>
}
