/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Tachyon server instance.
 *
 * ```typescript
 * import { TachyonRawServer } from 'tachyon';
 *
 * const server = new TachyonRawServer({ bindAddr: '0.0.0.0:8080' });
 *
 * // The handler runs in Rust coroutines — fast, safe, cross-platform
 * server.start((req) => ({
 *     status: 200,
 *     body: JSON.stringify({ message: 'Hello from Tachyon!' }),
 * }));
 * ```
 */
export declare class TachyonRawServer {
  constructor(config?: TachyonRawConfig | undefined | null)
  /**
   * Start the server with a JavaScript handler function.
   *
   * The handler is called for each HTTP request from a Rust coroutine.
   * It receives a `TachyonRequest` and must return a `TachyonResponse`.
   *
   * The server runs on background threads — Node's event loop stays free.
   */
  start(handler: (arg: TachyonRawRequest) => TachyonRawResponse): void
}

/**
 * Server configuration exposed to TypeScript.
 *
 * ```typescript
 * import { TachyonRawConfig } from 'tachyon';
 *
 * const config = new TachyonRawConfig();
 * config.bindAddr = '0.0.0.0:8080';
 * config.workers = 4;
 * ```
 */
export interface TachyonRawConfig {
  /** Address to bind (default: "0.0.0.0:3000") */
  bindAddr?: string
  /** Number of worker threads (default: CPU count) */
  workers?: number
  /** Coroutine stack size in KB (default: 64) */
  stackSizeKb?: number
  /** Buffer pool size per worker (default: 512) */
  buffersPerWorker?: number
  /** Buffer size in bytes (default: 8192) */
  bufferSize?: number
  /** Handler timeout in seconds (default: 30) */
  timeoutSecs?: number
  /** Enable TCP_NODELAY (default: true) */
  tcpNodelay?: boolean
  /** Enable SO_REUSEPORT (default: true, Linux/BSD only) */
  reusePort?: boolean
  /** Enable TCP Fast Open (default: true, Linux only) */
  tcpFastopen?: boolean
  /** SO_BUSY_POLL microseconds (default: 0 = disabled, requires root) */
  busyPollUs?: number
  /** SO_RCVBUF in bytes (default: 0 = OS default) */
  recvBufSize?: number
  /** SO_SNDBUF in bytes (default: 0 = OS default) */
  sendBufSize?: number
  /** Security header preset: "none" | "basic" | "strict" (default: "basic") */
  security?: string
  /**
   * Minimum body size in bytes to trigger gzip compression.
   * 0 = compress all, -1 = disabled. Default: 1024 (1KB).
   */
  compressionThreshold?: number
}

/** A single HTTP header key-value pair. */
export interface TachyonRawHeader {
  name: string
  value: string
}

/**
 * A typed JSON node for zero-alloc serialization via Rust's JsonWriter.
 * Supports any JSON shape: flat objects, nested objects, arrays, primitives.
 *
 * ```typescript
 * return {
 *   status: 200,
 *   json: [
 *     { key: "message", value: "Hello, World!" },
 *     { key: "id", value: "42", valueType: "number" },
 *     { key: "user", valueType: "object", children: [
 *       { key: "name", value: "Aaron" },
 *       { key: "age", value: "25", valueType: "number" },
 *     ]},
 *     { key: "tags", valueType: "array", children: [
 *       { value: "fast" },
 *       { value: "42", valueType: "number" },
 *     ]},
 *   ],
 * };
 * ```
 */
export interface TachyonRawJsonField {
  /** Object key. Omit for array elements. */
  key?: string
  /** Scalar value as string. Ignored for "object"/"array" types. */
  value?: string
  /** "string" (default) | "number" | "bool" | "null" | "raw" | "object" | "array" */
  valueType?: string
  /** Child fields for "object" or "array" types. */
  children?: Array<TachyonRawJsonField>
}

/**
 * Parsed HTTP request exposed to TypeScript callbacks.
 *
 * ```typescript
 * server.handle(({ method, path, body }) => {
 *     console.log(req.method, req.path);
 *     return { status: 200, body: '{"ok": true}' };
 * });
 * ```
 */
export interface TachyonRawRequest {
  method: string
  path: string
  body?: string
  headers: Array<TachyonRawHeader>
}

/**
 * Response from TypeScript handler.
 *
 * Three response paths (priority: `json` > `array` > `body`):
 *
 * ```typescript
 * // 1. json — object fields, serialized as {...} by Rust's zero-alloc JsonWriter
 * return { status: 200, json: [{ key: "message", value: "sucesso" }] };
 *
 * // 2. array — array elements, serialized as [...] by Rust's zero-alloc JsonWriter
 * return { status: 200, array: [{ value: "item1" }, { value: "42", valueType: "number" }] };
 *
 * // 3. body — plain text or custom content type
 * return { status: 200, body: "Hello!", contentType: "text" };
 * ```
 */
export interface TachyonRawResponse {
  status?: number
  /**
   * Plain body string. Used with `contentType` to set the response type.
   * Lowest priority — ignored if `json` or `array` is present.
   */
  body?: string
  /** "json" | "text" | "html" (default: "json"). Only applies to `body`. */
  contentType?: string
  /** Custom HTTP headers as key-value pairs (e.g., CORS, Cache-Control). */
  headers?: Array<TachyonRawHeader>
  /**
   * JSON object — fields serialized as `{...}` by Rust's zero-alloc JsonWriter.
   * Bypasses `JSON.stringify()` entirely.
   */
  json?: Array<TachyonRawJsonField>
  /** JSON array — elements serialized as `[...]` by Rust's zero-alloc JsonWriter. */
  array?: Array<TachyonRawJsonField>
}
