/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Turbine server instance.
 *
 * ```typescript
 * import { TachyonRawServer } from 'turbine';
 *
 * const server = new TachyonRawServer({ bindAddr: '0.0.0.0:8080' });
 *
 * // The handler runs in Rust coroutines — fast, safe, cross-platform
 * server.start((req) => ({
 *     status: 200,
 *     body: JSON.stringify({ message: 'Hello from Turbine!' }),
 * }));
 * ```
 */
export declare class TachyonRawServer {
  constructor(config?: TurbineRawConfig | undefined | null)
  /**
   * Start the server with a JavaScript handler function.
   *
   * The handler is called for each HTTP request from a Rust coroutine.
   * It receives a `TurbineRequest` and must return a `TurbineResponse`.
   *
   * The server runs on background threads — Node's event loop stays free.
   */
  start(handler: (arg: TachyonRawRequest) => TachyonRawResponse): void
}

/**
 * Parsed HTTP request exposed to TypeScript callbacks.
 *
 * ```typescript
 * server.handle(({ method, path, body }) => {
 *     console.log(req.method, req.path);
 *     return { status: 200, body: '{"ok": true}' };
 * });
 * ```
 */
export interface TachyonRawRequest {
  method: string
  path: string
  body?: string
}

/** Response from TypeScript handler. */
export interface TachyonRawResponse {
  status?: number
  body?: string
  /** "json" | "text" | "html" (default: "json") */
  contentType?: string
}

/**
 * Server configuration exposed to TypeScript.
 *
 * ```typescript
 * import { TurbineRawConfig } from 'turbine';
 *
 * const config = new TurbineRawConfig();
 * config.bindAddr = '0.0.0.0:8080';
 * config.workers = 4;
 * ```
 */
export interface TurbineRawConfig {
  /** Address to bind (default: "0.0.0.0:3000") */
  bindAddr?: string
  /** Number of worker threads (default: CPU count) */
  workers?: number
  /** Coroutine stack size in KB (default: 64) */
  stackSizeKb?: number
  /** Buffer pool size per worker (default: 512) */
  buffersPerWorker?: number
  /** Buffer size in bytes (default: 8192) */
  bufferSize?: number
  /** Handler timeout in seconds (default: 30) */
  timeoutSecs?: number
  /** Enable TCP_NODELAY (default: true) */
  tcpNodelay?: boolean
  /** Enable SO_REUSEPORT (default: true, Linux/BSD only) */
  reusePort?: boolean
  /** Enable TCP Fast Open (default: true, Linux only) */
  tcpFastopen?: boolean
  /** SO_BUSY_POLL microseconds (default: 0 = disabled, requires root) */
  busyPollUs?: number
  /** SO_RCVBUF in bytes (default: 0 = OS default) */
  recvBufSize?: number
  /** SO_SNDBUF in bytes (default: 0 = OS default) */
  sendBufSize?: number
}
